# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: ls -al && pwd

- script: sudo apt update && sudo apt install openjdk-8-jdk
  displayName: 'installing openjdk'

- script: ./build.sh
  displayName: 'run the build script'
  
- script: mv ROOT.war ROOT$(Build.BuildID).war && ls -al
  displayName: 'list files & rename ROOT.war'

  settings
  
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
